#[derive(Debug, Eq, PartialEq, Copy, Clone)]
pub enum Token<'input> {
    CurlyBraceOpen,
    CurlyBraceClose,
    ParenOpen,
    ParenClose,
    SquareBracketOpen,
    SquareBracketClose,
    Period,
    Comma,
    Identifier(&'input str),
    StringLiteral(&'input str),
    StringTemplateLiteral(&'input str),
    NumberLiteral(&'input str),
    Do,
    Let,
    Fun,
    If,
    Then,
    Else,
    Case,
    Of,
    End,
    Type,
    Data,
    Equal,
    Pipe,
    Import,
    Colon,
    Arrow
}