[package]
name = "calima"
version = "0.1.0"
authors = ["SpacialCircumstances <SpacialCircumstances@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.18.1"

[dev-dependencies]
goldenfile = "1.1.0"

[dependencies]
lalrpop-util = "0.18.1"
codespan-reporting = "0.9.4"
